#!/bin/sh
set -e

echo "#!/bin/sh" >  /usr/local/bin/healthcheck
chmod a+x /usr/local/bin/healthcheck

if [ "${STOP_ON_BAD_HEALTH}" = "true" ]
    then echo "badhealth='apachectl stop'" >> /usr/local/bin/healthcheck
    then echo "badhealth='true'" >> /usr/local/bin/healthcheck
fi

if [ "${KNX_INTERFACE}" != "" ]; then
    echo "starting knxd"
    knxd -i $KNX_INTERFACE -e $KNX_PA $KNXD_PARAMETERS
    chmod a+w /tmp/eib
    echo "if ! pidof knxd >/dev/null; then echo 'Error: knxd not running'; \$badhealth; exit 1; fi" >> /usr/local/bin/healthcheck
    echo "if [ ! -e /tmp/eib ]; then echo 'Error: knxd socked does not exist'; \$badhealth; exit 1; fi" >> /usr/local/bin/healthcheck
fi

CGI_URL_PATH=${CGI_URL_PATH:-/cgi-bin/}
if [ "${CGI_URL_PATH:-/cgi-bin/}" != "/cgi-bin/" ]; then
    echo "Non default CGI_URL_PATH detected: '$CGI_URL_PATH'"

    # Tell the CometVisu to path to the login
    echo '<FilesMatch "visu_config.*xml$">'                             >  /var/www/html/.htaccess
    echo "    Header set X-CometVisu-Backend-LoginUrl ${CGI_URL_PATH}l" >> /var/www/html/.htaccess
    echo '</FilesMatch>'                                                >> /var/www/html/.htaccess

    # Pass CometVisu the resource path during the login
    sed -i 's@\\\"s\\\":\\\"SESSION\\\".*}\"@\\\"s\\\":\\\"SESSION\\\", \\\"c\\\": {\\\"baseURL\\\": \\\"'"$CGI_URL_PATH"'\\\"} }"@' /usr/lib/cgi-bin/l
fi

if [ "${BACKEND_PROXY_SOURCE}" != "" ] && [ "${BACKEND_PROXY_TARGET}" != "" ]; then
    echo "proxying ${BACKEND_PROXY_SOURCE} -> ${BACKEND_PROXY_TARGET}"
    echo "ProxyPass ${BACKEND_PROXY_SOURCE} ${BACKEND_PROXY_TARGET}"        >  $APACHE_CONFDIR/conf-available/cv-proxy.conf
    echo "ProxyPassReverse ${BACKEND_PROXY_TARGET} ${BACKEND_PROXY_SOURCE}" >> $APACHE_CONFDIR/conf-available/cv-proxy.conf

    a2enmod proxy_http > /dev/null
    a2enconf cv-proxy.conf > /dev/null
fi

rm /var/log/apache2/access.log
if [ "${ACCESS_LOG}" = "true" ]
    then ln -s /dev/stdout /var/log/apache2/access.log
    else ln -s /dev/null /var/log/apache2/access.log
fi

echo "if ! curl -f -s http://localhost/ >/dev/null; then echo 'Error: apache not responding'; \$badhealth; exit 1; fi" >> /usr/local/bin/healthcheck

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

exec "$@"