#!/bin/bash
echo Content-Type: application/json
echo Content-Encoding: gzip
echo

RRD=`echo "$QUERY_STRING" | sed -n 's/^.*rrd=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
DS=`echo "$QUERY_STRING" | sed -n 's/^.*ds=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
START=`echo "$QUERY_STRING" | sed -n 's/^.*start=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
END=`echo "$QUERY_STRING" | sed -n 's/^.*end=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
RES=`echo "$QUERY_STRING" | sed -n 's/^.*res=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`

rrdtool fetch /var/www/rrd/$RRD $DS -s$START -e$END -r$RES | \
{ while read line ;
do
    if [[ "$line" == *:* ]]          # matching lines with ":"
    then
    arr=(${line//: / })              # splits string with ": " in array
    timestamp="${arr[0]}000"         # first is the time stamp
    content=${arr[@]:1}              # all but the first
    content_text=${content// /\",\"} # join with "," in between
    data+="[$timestamp,[\"$content_text\"]],"
fi
done
echo "[${data%?}]" | gzip -c         # cuts last char of $data and makes [] around
}
