#!/bin/bash
set -o xtrace

echo docker build -f $DOCKERFILE_PATH --build-arg MY_ARG=$MY_ARG --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg COMMIT_MSG=$COMMIT_MSG --build-arg DOCKER_REPO=$DOCKER_REPO --build-arg CACHE_TAG=$CACHE_TAG --build-arg IMAGE_NAME=$IMAGE_NAME -t $IMAGE_NAME .
env
ls -l
pwd
echo DOCKER_TAG $DOCKER_TAG
echo CACHE_TAG=$CACHE_TAG
echo BUILD_PATH=$BUILD_PATH
ls -l $DOCKERFILE_PATH

#docker build -f $DOCKERFILE_PATH --build-arg MY_ARG=$MY_ARG --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg COMMIT_MSG=$COMMIT_MSG --build-arg DOCKER_REPO=$DOCKER_REPO --build-arg IMAGE_NAME=$IMAGE_NAME -t $IMAGE_NAME .
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
