#!/bin/bash
echo docker build --build-arg MY_ARG=$MY_ARG --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg COMMIT_MSG=$COMMIT_MSG --build-arg DOCKER_REPO=$DOCKER_REPO --build-arg CACHE_TAG=$CACHE_TAG --build-arg IMAGE_NAME=$IMAGE_NAME -t $IMAGE_NAME .

docker build --build-arg MY_ARG=$MY_ARG --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg COMMIT_MSG=$COMMIT_MSG --build-arg DOCKER_REPO=$DOCKER_REPO --build-arg CACHE_TAG=$CACHE_TAG --build-arg IMAGE_NAME=$IMAGE_NAME -t $IMAGE_NAME .
