#!/bin/bash
set -o xtrace

#echo docker build -f $DOCKERFILE_PATH --build-arg MY_ARG=$MY_ARG --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg COMMIT_MSG=$COMMIT_MSG --build-arg DOCKER_REPO=$DOCKER_REPO --build-arg CACHE_TAG=$CACHE_TAG --build-arg IMAGE_NAME=$IMAGE_NAME -t $IMAGE_NAME .
#env
#ls -l
#pwd
#echo DOCKER_TAG $DOCKER_TAG
#echo CACHE_TAG=$CACHE_TAG
#echo BUILD_PATH=$BUILD_PATH
#ls -l $DOCKERFILE_PATH

if [[ $IMAGE_NAME =~ ":v" ]]; then 
  echo "tag"; 
  BUILD_BRANCH=tags/$(echo $IMAGE_NAME | sed 's/.*:\(v.*\).*/\1/')
else 
  echo "branch"; 
  BUILD_BRANCH=$(echo $IMAGE_NAME | sed 's/.*:\(.*\).*/\1/')
fi

echo BUILD_BRANCH=$BUILD_BRANCH

#docker build -f $DOCKERFILE_PATH --build-arg MY_ARG=$MY_ARG --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg COMMIT_MSG=$COMMIT_MSG --build-arg DOCKER_REPO=$DOCKER_REPO --build-arg IMAGE_NAME=$IMAGE_NAME -t $IMAGE_NAME .
docker build -f ${DOCKERFILE_PATH:-Dockerfile} --build-arg BUILD_BRANCH=$BUILD_BRANCH -t $(echo $DOCKER_REPO:$DOCKER_TAG | sed "s#,# -t $DOCKER_REPO:#g") .
